FROM golang:1.25-alpine

RUN apk add --no-cache git

WORKDIR /app

# Copy go mod files first (better caching)
COPY src/go.mod src/go.sum ./
RUN go mod download
COPY src/ .


# Build Go binary
RUN go build -o app .

EXPOSE 8000

CMD ["./app"]
