FROM golang:1.25-alpine

RUN apk add --no-cache git

WORKDIR /app

# Copy go mod files first (better caching)
COPY backend/src/go.mod backend/src/go.sum ./
RUN go mod download

# Copy entire backend source into /app
COPY backend/src/ .

# Build Go binary
RUN go build -o app .

EXPOSE 8000

CMD ["./app"]
